version: "3.8"

services:

    nodejs:
        container_name: nodejs
        build: .
        command: >
            bash -c 'echo "Node.js version $(node --version),
            npm version $(npm --version)"'
